apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /data-mounted-as
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate