apiVersion: v1
kind: Pod
metadata:
  name: annotations-pod
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
