apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Migrating data to reporting server...
          restartPolicy: OnFailure

