apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ninad
  name: ninad
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: ninad
  type: NodePort
status:
  loadBalancer: {}
