apiVersion: v1
kind: Service
metadata:
  name: springdb-mysql
  labels:
    app: springdb-mysql
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: springdb
    tier: mysql