apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: springdb-mysql
  labels:
    app: springdb
spec:
  selector:
    matchLabels:
      app: springdb
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springdb
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.3
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: rootpassword
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: name
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: user
#            secretKeyRef:
#              name: secret-config
#              key: username              
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: springdb-pvc
