apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springdb-pvc
  labels:
    app: springdb
spec:
  storageClassName: storageclass-generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi